import './globals.css'
import './layout.style.css'
import type { Metadata } from 'next'
import { poppins } from './ui/fonts'
import { Header } from './components/header/header.component'
import { Footer } from './components/footer/footer'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {

  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <header>
          <Header/>
        </header>
        <nav>{children}</nav>
        <footer>
          <Footer/>
        </footer>
      </body>
    </html>
  )
}
