import React from "react";
import type { Metadata } from "next";
import './home.style.css'
import { HomeInformation } from "./components/homeInformation/homeInformation";
import { Presentation } from "./components/integrantes/presentation.component";


export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <div>
      <HomeInformation/>
      <Presentation/>
    </div>
  );
}