import React from "react";
import type { Metadata } from "next";
import { RooterPresentation } from "../components/rooterPresentation/rooterPresentation.component";
import { RooterImage } from "../components/rooterPhoto/rooterPhoto.component";
import { Utilities } from "../components/utilities/utilities.component";
import { OverallDimensions } from "../components/overallDimensions/overallDimensions.component"
import { RooterSwiper } from "../components/rooterSwiper/rooterSwiper.component";
import { Blueprints } from "../components/blueprints/blueprints.component";
import { FrecuentQuestions } from "../components/frecuentQuestions/frecuentQuestions.component";


export const metadata: Metadata = {
  title: "Rooter",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <div className="bg-common-white">
      <RooterPresentation/>
      <RooterImage/>
      <Utilities/>
      <OverallDimensions/>
      <RooterSwiper/>
      <Blueprints/>
      <FrecuentQuestions/>
    </div>
  );
}