import React from "react";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Tripode",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <div>
        hola
    </div>
  );
}